# Generated by Django 4.1.2 on 2022-11-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='zip_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
