# Generated by Django 4.1.2 on 2022-11-26 20:58

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_account_warnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to=users.models.get_file_path),
        ),
    ]
