# Generated by Django 4.1.2 on 2022-12-08 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_alter_account_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.FloatField()),
                ('status', models.BooleanField(default=True, help_text="True=Show, False=Don't Show")),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_data', models.DateTimeField(auto_now=True)),
                ('review_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_giver', to=settings.AUTH_USER_MODEL)),
                ('review_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
