# Generated by Django 4.1.2 on 2022-12-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_reviewrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
