# Generated by Django 4.1.2 on 2022-12-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_account_accoount_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accoount_balance',
            new_name='account_balance',
        ),
    ]
