# Generated by Django 4.1.2 on 2022-12-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_accoount_balance_account_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
