# Generated by Django 4.1.2 on 2022-12-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_account_average_rating_account_rating_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='account',
            name='rating_total',
        ),
        migrations.RemoveField(
            model_name='account',
            name='warnings',
        ),
    ]
