# Generated by Django 4.1.2 on 2022-12-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_account_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='approved',
            field=models.BooleanField(default=False, help_text='False=Not Approved, True=Approaved'),
        ),
    ]
