# Generated by Django 4.1.2 on 2022-12-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_account_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='approved',
            field=models.BooleanField(blank=True, default=False, help_text='False=Not Approved, True=Approaved'),
        ),
    ]
