# Generated by Django 4.1.2 on 2022-12-08 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bidding_price',
            new_name='bid_starting_price',
        ),
        migrations.AddField(
            model_name='product',
            name='bid_current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_price', models.FloatField()),
                ('bid_status', models.CharField(choices=[('Pending', 'Pending'), ('Bid_Accepted', 'Bid_Accepted'), ('Bid_Rejected', 'Bid_Rejected')], default='Pending', max_length=150)),
                ('quantity', models.IntegerField()),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
