# Generated by Django 4.1.2 on 2022-12-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_bid_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Outforshipping', 'Out for Shipping'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
    ]
